version: '2.2'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tars
      POSTGRES_USER: tars
      POSTGRES_PASSWORD: tars
    healthcheck:
      test: [ 'CMD', 'pg_isready', "-q", "-d", "tars", "-U", "tars" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

  eclipse-mosquitto:
    stdin_open: true
    tty: true
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    container_name: mosquitto
    volumes:
      - /mosquitto/config:/mosquitto/config
      - /mosquitto/data:/mosquitto/data
      - /mosquitto/log:/mosquitto/log
    image: eclipse-mosquitto
    healthcheck:
      test: [ "CMD-SHELL", "mosquitto -c /mosquitto/config/mosquitto.conf -v > /dev/null 2>&1 || exit 1" ]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 3s
