syntax = "proto3";

option java_package = "grpc.entity.State";
option java_outer_classname = "StateUpdate";

service StateService {

  rpc UpdateState(StateUpdate) returns (StateResponse) {}
  rpc GetState(DeviceID) returns (StateResponse) {}

}

message StateUpdate {
  string device_id = 1;
  string tenant_id = 2;
  string state = 3;
  string deviceName = 4;
  string info = 5;
  
}

message DeviceID {
  string device_id = 1;
  optional string device_name = 2;
  string tenant_id = 3;
}

message StateResponse {
  string status = 1;
  string payload = 2;
}