akka {
  actor {
    provider = "cluster"
  }

  remote {
    artery {
      transport = tcp
      canonical.hostname = 127.0.0.1
      #canonical.hostname = 37.27.27.61
      #canonical.hostname = 37.27.92.245
      #canonical.hostname = 37.27.32.165
      canonical.port = 2551
      #canonical.port = 2552
      #canonical.port = 2553
      #canonical.port = 2554
    }
  }

  cluster {
    name = "middleware-supervisor"
    seed-nodes = [
      "akka://middleware-supervisor@127.0.0.1:2551",
      #"akka://middleware-supervisor@37.27.27.61:2552",
      #"akka://middleware-supervisor@37.27.92.245:2553",
      #"akka://middleware-supervisor@37.27.32.165:2554",
    ]
    downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"
    sharding.number-of-shards = 10
  }
}

akka.cluster.sharding {
  # Enable Remember Entities feature to ensure entities are persisted across restarts
  remember-entities = on

  # Specify the persistence store for sharded entities
  remember-entities-store = eventsourced

  # Optional: Control the retention policy for sharded entity state
  # If you want to retain entities across cluster restarts even if not active,
  # use the "event-sourced" persistence method which will recreate entities from events
  # By default, eventsourced will restore entity state using event sourcing.
  remember-entities-store = eventsourced
}

