akka {
  actor {
    provider = "cluster"
  }

  remote {
    artery {
      transport = tcp
      canonical.hostname = 127.0.0.1
      #canonical.hostname = 37.27.27.61
      #canonical.hostname = 37.27.92.245
      #canonical.hostname = 37.27.32.165
      canonical.port = 2551
      #canonical.port = 2552
      #canonical.port = 2553
      #canonical.port = 2554
    }
  }

  cluster {
    name = "middleware-supervisor"
    seed-nodes = [
      "akka://middleware-supervisor@127.0.0.1:2551",
      #"akka://middleware-supervisor@37.27.27.61:2552",
      #"akka://middleware-supervisor@37.27.92.245:2553",
      #"akka://middleware-supervisor@37.27.32.165:2554",
    ]
    downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"
    sharding.number-of-shards = 10
  }
}



